echo Installing Ros Essentials...
adb push ~/ROS_ANDROID/rospy_android/com.googlecode.pythonforandroid /sdcard/com.googlecode.pythonforandroid
echo Copying example scripts...
adb push ~/ROS_ANDROID/rospy_android/sl4a /sdcard/sl4a
echo Installation Complete
